### ISSUE TITLE
Opdracht, presentatie & readme

### ISSUE THREAD

**Issue by KoopReynders** [beemstb002/BrowserTechnologies#10]
Readme mist een duidelijk opbouw. Zie Moodle voor oplevercriteria. 
Code niet goed. Progressive Enhancement niet goed.

**Comment by beemstb002** [comment]
Code en Enhancement verbeterd. De readme was samen met mijn presentatie wel duidelijk, maar heb deze nu aangevuld waardoor deze ook zonder presentatie duidelijk is.

**Comment by KoopReynders** [comment]
Ik zie het niet. Heb je wel gecommit ?

**Comment by beemstb002** [comment]
Staat in de map her.

**Comment by KoopReynders** [comment]
oh man ! Het hele idee van Git is dat je verbeteringen op je code kan doorvoeren en niet allemaal mappen naast elkaar hoeft bij te houden ! 

Check. Gezien
