### ISSUE TITLE
Welke functionaliteit bied je als JS niet geladen wordt?

### ISSUE THREAD

**Issue by krijnhoetmer** [beemstb002/BrowserTechnologies#3]
Ik zie een aantal knoppen, maar die doen niets. Wat is daarmee je plan? Probeer dat ook uit te werken in je markup (zonder de volledige back-end nodig te hebben).

**Comment by beemstb002** [comment]
PHP is daarvoor mijn fallback. Ik heb de knoppen nu in een `<form>` tag gezet waardoor er met PHP iets mee gedaan kan worden.
