### ISSUE TITLE
HTML en JavaScript zijn veel te afhankelijk van elkaar

### ISSUE THREAD

**Issue by krijnhoetmer** [beemstb002/BrowserTechnologies#4]
Wat als ik een nieuw product toevoeg in de HTML? Op dit moment moet je dan ook aanpassingen doen in je JavaScript, terwijl het idee van progressive enhancement (volgens mij) is dat je het als extra laag over je HTML heen legt. Kun je je JavaScript slimmer structureren, zodat het eigenlijk niet uit maakt welke/hoeveel producten je in je HTML hebt staan?

**Comment by beemstb002** [comment]
JavaScript opnieuw geschreven zodat als er in de HTML een item toegevoegd wordt, dat automatisch ook werkt in de JavaScript. Voor beide scenario's (wel Drag & Drop support en geen).
