### ISSUE TITLE
Werkt `classList` overal?

### ISSUE THREAD

**Issue by krijnhoetmer** [beemstb002/BrowserTechnologies#5]
Je gebruikt deze feature, maar wat als een browser dit niet ondersteunt? Bekijk dit ook voor andere features, zoals een simpele `addEventListener`. Kijk ook naar Cutting the Mustard technieken.

**Comment by beemstb002** [comment]
`className` gebruikt ipv `classList`. Deze wordt wel door iedere browser gesupport en ik wil in dit geval maar 1 class toevoegen en er zijn geen classes die hierdoor worden overschreven.
