### ISSUE TITLE
Wat is Storage in `typeof(Storage)` ?

### ISSUE THREAD

**Issue by krijnhoetmer** [beemstb002/BrowserTechnologies#6]
Wat doet deze check? Heb je deze goed getest?

**Comment by beemstb002** [comment]
Volgens W3schools checkt deze of localStorage en sessionStorage ondersteund worden door de browser.

Bron: http://www.w3schools.com/html/html5_webstorage.asp

**Comment by KoopReynders** [comment]
Ik heb altijd geleerd dat W3schools een slecht raadgever is. Daarnaast moet je dit zelf kunnen beredeneren.
