### ISSUE TITLE
Gebruik van `!important` in je CSS

### ISSUE THREAD

**Issue by krijnhoetmer** [beemstb002/BrowserTechnologies#7]
Heb je dit echt nodig daar? Probeer jezelf aan te leren `!important` niet te gebruiken. Misschien is het gewoon een probleem in je selectors (specificity), dat je makkelijk kunt oplossen.

**Comment by beemstb002** [comment]
Opgelost waar dat kon met specificity. Staat er nog 1 in die daarmee niet opgelost kan worden.
