### ISSUE TITLE
User agent sniffing zet je op het verkeerde been

### ISSUE THREAD

**Issue by krijnhoetmer** [beemstb002/BrowserTechnologies#9]
Probeer niet te denken in twee varianten, maar in een verrijking/enhancement van je core functionaliteit. Door user agent sniffing in te zetten, kun je niet anders dan in twee versies denken. Los daarvan: UA sniffing gaat heel snel heel verkeerd. Lees bijvoorbeeld http://www.sitepoint.com/opera-10-user-agent/ of https://blogs.msdn.microsoft.com/ie/2011/04/15/the-ie10-user-agent-string/ (wat in de toekomst ook gewoon nog gaat gebeuren).

**Comment by beemstb002** [comment]
Goed punt, beide artikelen gelezen en deze problemen wil je absoluut vermeiden. Verrijking is inderdaad het juiste uitgangspunt.
